# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  # jobs:
  commands:
    # post_checkout:
      # Cancel building pull requests when there aren't changed in the docs directory or YAML file.
      # You can add any other files or directories that you'd like here as well,
      # like your docs requirements file, or other files that will change your docs build.
      #
      # If there are no changes (git diff exits with 0) we force the command to return with 183.
      # This is a special exit code on Read the Docs that will cancel the build immediately.
      - |
        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/main -- doc/ .readthedocs.yaml;
        then
          exit 183;
        fi
      # - su && touch /usr/lib/foo
      # - su && ls /usr/lib/foo
    # pre_create_environment:
      - git clone --depth 1 https://github.com/CrayLabs/SmartRedis.git smartredis
      - git clone --depth 1 https://github.com/CrayLabs/SmartDashboard.git smartdashboard
    # post_create_environment:
      - pwd
      - python -m pip install .[dev,docs]
      - cd smartredis; python -m pip install .
      - cd smartredis/doc; doxygen Doxyfile_c; doxygen Doxyfile_cpp; doxygen Doxyfile_fortran
      - ln -s smartredis/examples ./examples
      - cd smartdashboard; python -m pip install .
      - smart build --device cpu --dragon -v
      - find . -name "libdragon.so*"
      - |
        export LD_LIBRARY_PATH=$PWD/smartsim/_core/.dragon/dragon-0.9/lib/:$LD_LIBRARY_PATH &&
        make docs &&
        mkdir -p _readthedocs/ &&
        cp -r doc/_build/html/ _readthedocs/
      


      # - smart build --device cpu --dragon -v
      # - cp ./smartsim/_core/.dragon/dragon-0.9/lib/libdragon.so /usr/lib/
      

  

      # - export $(cat /home/docs/checkouts/readthedocs.org/user_builds/smartsim/envs/755/lib/python3.10/site-packages/smartsim/_core/.dragon/.env | grep DRAGON_INCLUDE_DIR)
      # - export LD_LIBRARY_PATH=$DRAGON_INCLUDE_DIR:$LD_LIBRARY_PATH
      # - echo $DRAGON_INCLUDE_DIR
      # - echo $LD_LIBRARY_PATH
      # - ls
      # - pwd
      # - find /home/docs/checkouts/readthedocs.org/user_builds/smartsim/envs/755/lib/python3.10/site-packages/smartsim/_core/.dragon -name ".env"
      # - which smart
      # - smart site
      
    # pre_build:
      - pip install typing_extensions==4.8.0
      - pip install pydantic==1.10.13
      - python -m sphinx -b linkcheck doc/ $READTHEDOCS_OUTPUT/linkcheck

    # build: 
      

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: doc/conf.py
  fail_on_warning: true
